#!/bin/bash

#Anthony created on 9/28/2021

# This program tests for user input parameters, and prints the parameter to screen.
 
if [ "${#}" -eq "1" ]; then
  printf "${@}\n";
else
  printf 'There is an error. In order to use this program, please indicate your (1) parameter after run command.'"\n";
  exit 1;
fi 
#EOF
