#!/bin/bash

# Anthony, created on 11/12/21

# Assigning a storage size for each directory.

declare -A users;

for lines in $(egrep -v "(nologin|false)$" /etc/passwd); do 
   username="$(echo ${lines} | cut -d ":" -f1)";
   homedir="$(echo ${lines} | cut -d ":" -f6)"; 
   users[${username}]=${homedir};
done

for i in ${!users[*]}; do 
   echo "${i} -> ${users[${i}]} ($(du -sh ${users[${i}]} | cut -f1))";
done
#EOF
